### ISSUE TITLE
Problems with interpreting C-Style unsigned Hex-Numbers

### ISSUE THREAD

**Issue by Wastus** [mateuszchudyk/vscode-hexinspector#2]
In C and C++ source code if you define an unsigned literal the HexInspector gets it very wrong.

For example 0x39U

It interprets it as 2 bytes, and fails interpreting the second byte but no error is shown.

![Example](https://user-images.githubusercontent.com/16320076/61115209-461d0c00-a492-11e9-9967-c28dd0b87342.png)

A fix might be to throw away non-hex digits at the end.

**Comment by mateuszchudyk** [comment]
Yes, the problem is that suffixes are not supported for now. I'll try to add that functionality as soon as possible. Thank you for reporting this issue.

**Comment by mateuszchudyk** [comment]
Done (d792c0aa08663865ceeaa9973178f634a9fb44a4).
