### ISSUE TITLE
decimal and binary

### ISSUE THREAD

**Issue by irvnriir** [mateuszchudyk/vscode-hexinspector#5]
it would be more useful with ability to use it on decimal and binary numbers .

**Comment by pidgeon777** [comment]
Yes I also second this request. Hovering on binary (0bXXXX) or decimal numbers should also lead the extension to show a popup with the conversion results. It would be super useful, and maybe easier to implement?

**Comment by mateuszchudyk** [comment]
The idea was to create extension only for hex values but I'll consider extending functionality by bin and dec values.

**Comment by heartacker** [comment]
@mateuszchudyk that will be great if we have it

**Comment by mateuszchudyk** [comment]
I started adding these features.

**Comment by mateuszchudyk** [comment]
Merged to the master and deployed to Marketplace.
