### ISSUE TITLE
Support showing a list of bits that are set

### ISSUE THREAD

**Issue by thops** [mateuszchudyk/vscode-hexinspector#8]
For my uses, it would be nice to list the bit positions that are set.
(This might be best disabled by default and have configuration item to enable. It probably isn't a normal use.)

In the following example, I would like to quickly check if bits 16, 17 and 18 are set.
Ideally, I would be able to do this without tracking the positions myself.

> HexInspector: 0x700E2 (3B)
> 
> Decimal:  458,978
> Binary:   00000111 00000000 11100010
> Float32:  6.431651665588759e-40
> Float64:  2.267653e-318
> Chars:    â
> Size:     448.221 KiB
> 
> Little Endian

It would be nice to also have:
> Bits set: 1, 5, 6, 7, 16, 17, 18

or something along those lines

**Comment by mateuszchudyk** [comment]
Added in [v1.4.0](https://github.com/mateuszchudyk/vscode-hexinspector/releases/tag/v1.4.0).
